name: andreyka_piano
description: The phone piano made by Flutter and me ))

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  tonic: ^0.2.3
  flutter_midi: ^0.1.1+3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter






flutter:
  uses-material-design: true
  assets:
    - assets/sounds/Piano.sf2

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
